language: node_js
node_js:
  - '10'
  - '12'
branches:
  only:
  - master
# Handle git submodules yourself
git:
  submodules: false
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
before_script:
  - yarn lerna bootstrap
  - yarn lerna run bootstrap
script:
  - yarn lint
  - yarn test
