version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
  # these dependencies are intentionally included in
  # the test fixtures to see if the audit task works as designed
  - package_manager: "javascript"
    directory: "/packages/web-scripts/src/Tasks/AuditTasks/__fixtures__/12"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "geddy"
  - package_manager: "javascript"
    directory: "/packages/web-scripts/src/Tasks/AuditTasks/__fixtures__/30"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "geddy"
      - match:
          dependency_name: "bassmaster"
      - match:
          dependency_name: "uglify-js"
      - match:
          dependency_name: "chokidar"
