name: Publish

on:
  push:
    branches:
    - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: yarn install
      run: yarn
    - name: yarn build
      run: yarn build
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
    - name: release
      run: yarn release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
